apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-01T09:02:24Z"
  labels:
    app: web1
  name: web1
  namespace: default
  resourceVersion: "180675"
  uid: dbeb6a58-8f00-4488-bc40-ed8f03eade86
spec:
  clusterIP: 10.96.61.250
  clusterIPs:
  - 10.96.61.250
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31695
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

